- name: Hello World Sample
  hosts: all
  vars: 
    - target_dir : /usr/local
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Append test message on target dir
      become: yes
      become_user: ec2-user
      shell: 
        chdir: {{target_dir}}
        cmd: echo "test message" >> ansible_test_file

